export const TempData =[
    {
    "userId": 1,
    "id": 1,
    "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    
},
    {
    "userId": 1,
    "id": 2,
    "title": "qui est esse",
    
},
    ]

    export  var JSONDATALIST1 =	[
        {first_name:"Shop by Categories",},
        {first_name:"Baby & child helth",},
        {first_name:"Eye Care",},
        {first_name:"Foot Care",},
        {first_name:"First aids",},
        {first_name:"Hair Loss",},
        {first_name:"Hand Wash & Sanitizers",},
        {first_name:"Men's Health",},
        {first_name:"Men's toiletries",},
        {first_name:"Mouth,lips & oral care",},
        {first_name:"Sexual Wellbeing",},
        {first_name:"Skin Care",},
        {first_name:"Women's health"},
        {first_name:"Women's toiletries"},
        {first_name:"Anting Aging"},
        {first_name:"Baby & child vitamins"},
        {first_name:"Brain Supplements"},
        {first_name:"Immune Health"},
        {first_name:"Men's Health Supplements",},
        {first_name:"Multivitamins",},
        {first_name:"Pregnancy Supplements",},
        {first_name:"Skin, Nail & hair Care",},
        {first_name:"Mouth,lips & oral care",},
        {first_name:"Women's health Supplements",},
        {first_name:"Blood pressure Apparatus",},
        {first_name:"Glucose Monitors",},
        {first_name:"Nebulizers",},
        {first_name:"Acidity",},
        {first_name:"Acne",},
        {first_name:"Alzheimer",}, 
        {first_name:"Anaemia",},
        {first_name:"Angina",},
        {first_name:"Anxiety",},
        {first_name:"Appetite",},
        {first_name:"Arthritis",},
        {first_name:"Asthma",},
        {first_name:"Baby Care",},
        {first_name:"Bleeding Disorder",},
        {first_name:"Burn",},
        {first_name:"Canser/oncology",},
        {first_name:"Cns Stimulant",},
        {first_name:"Constipation",},
        {first_name:"Contrcapation",},
        {first_name:"Cough, cold & flu  ",},
        {first_name:"Dandruf",},
        {first_name:"Depression",},
        {first_name:"Diabetes",},
        {first_name:"Diarrhoea",},
        {first_name:"Ear Condition",},
        {first_name:"Epilepsy/Convulsion",},
        {first_name:"Fever",},
        {first_name:"Fungal",},
        {first_name:"Gastro Intestinal Motility Disorders",},
        {first_name:"General",},
        {first_name:"Gout",},
        {first_name:"Haemorrhoid",},
        {first_name:"Head Lice",},
        {first_name:"Hepatitis B Infection",},
        {first_name:"Herbal Products",},
        {first_name:"High Cholesterol"},
        {first_name:"Hormonal Therapy"},
        {first_name:"Hyperpigmentation"},
        {first_name:"Hypertension"},
        {first_name:"Hyperthyroidism",last_nam:"rehman",email:"zaka@gmail.com",gender:"male",ip_address:"8y28y892"},
        {first_name:"Impotence/Erectile Dysfunction (Ed)"},
        {first_name:"Infection"},
        {first_name:"Intravenous Fluids"},
        {first_name:"Liver Disease"},
        {first_name:"Malarial"},
        {first_name:"Menopause"},
        {first_name:"Migraine"},
        {first_name:"Nasal Congestion"},
        {first_name:"Neuropathic Pain"},
        {first_name:"Bone & Jointment Care"},
        {first_name:"Obesity"},
        {first_name:"Pain"},
        {first_name:"Parasitic Worms"},
        {first_name:"Parkinson's Disease"},
        {first_name:"Poisoning/Overdose"},
        {first_name:"Prostate"},
        {first_name:"Covid"},
        {first_name:"Psychosis"},
        {first_name:"Scabies"},
        {first_name:"Scar"},
        {first_name:"Schizophrenia"},
        {first_name:"Skin Infections"},
        {first_name:"Stroke"},
        {first_name:"Sun Protectors"},
        {first_name:"Supplement"},
        {first_name:"Surgicals"},
        {first_name:"Stomach Ulcer/Reflux/Flatulence"},
        {first_name:"Urinary Tract Infection (UTI)"},
        {first_name:"Vaccines"},
        {first_name:"Vaginal Conditions"},
        {first_name:"Vertigo"},
        {first_name:"Viral"},
        {first_name:"Vomitting/Emesis"},
        {first_name:"Abdominal Pain"},
        {first_name:"Antiperspirant"},
        {first_name:"Consumer Product"},
        {first_name:"Essential Oils"},
        {first_name:"Heart diseases",},
        {first_name:"Kidney Disease/Stone",},
        {first_name:"Mosquito Repellent",},
        {first_name:"Muscle & Body Support",},
        {first_name:"Piles",},
        {first_name:"Probiotics",},
        {first_name:"Skin Inflammation",},
        {first_name:"Sleep Disorder",},
        {first_name:"Warts/Calluses/Other",},
    ];